type: efficientvit_sam
name: efficientvit_sam_l1_vit_h-r20230920
display_name: EfficientViT-SAM-l1 (ViT-Huge)
encoder_model_path: https://github.com/healthonrails/annolid/releases/download/v1.1.3/efficientvit_sam_l1_vit_h.encoder.onnx
decoder_model_path: https://github.com/healthonrails/annolid/releases/download/v1.1.3/efficientvit_sam_l1_vit_h.decoder.onnx
target_size: 1024
