- model_name: "efficientvit_sam_l0_vit_h-r20230920"
  config_file: ":/efficientvit_sam_l0_vit_h.yaml"
- model_name: "efficientvit_sam_l1_vit_h-r20230920"
  config_file: ":/efficientvit_sam_l1_vit_h.yaml"
