# Installs dependencies for Annolid managed by Anaconda.
#
name: annolid-dev
#prefix: /path/to/my/envs/annolid-dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.10
  - pip
  - cython
  - pytorch::torchvision>=0.19
  - pytorch::pytorch>=2.5
  - ffmpeg
  - matplotlib
  - git
  - curl
  - unzip
  - pyqt
  - qtpy
  - opencv
  - pyqtwebengine
  - conda-forge::bash
  - numpy>=1.18.2
  - scipy>=1.5.2
  - easydict>=1.9
  - pip:
    - pillow>=8.3.1
    - imgviz>=1.7.5
    # needed on KDE/Qt envs for matplotlib
    - PyYAML>=5.3
    - pandas>=1.1.3
    - pycocotools>=2.0.2
    - tensorboard>=2.3.0
    - imageio>=2.8.0
    - imageio-ffmpeg>=0.4.2
    - dataclasses>=0.6; python_version < '3.7'
    - jupyter-book==0.12.1
    - e .
