# Installs dependencies for Annolid managed by Anaconda. 
#
name: annolid-env
#prefix: /path/to/my/envs/annolid-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.7
  - pip
  - cython 
  - pytorch::torchvision
  - pytorch::pytorch >=1.4.0
  - cudatoolkit
  - cudnn
  - ffmpeg
  - pytorch::cuda100
  - matplotlib
  - git 
  - curl 
  - unzip 
  - conda-forge::bash
  - numpy>=1.18.2
  - scipy>=1.5.2
  - easydict>=1.9
  - pip:
    - pillow>=8.3.1 
    - pycocotools>=2.0.2 
    # needed on KDE/Qt envs for matplotlib
    - PyQt5>=5.15.1
    - labelme>=4.5.6
    - opencv-python==4.1.2.30
    - opencv-contrib-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
    - PyYAML>=5.3
    - decord>=0.4.0
    - torch>=1.4.0
    - torchvision>=0.5.0
    - pandas>=1.1.3
    - pycocotools>=2.0.2
    - tensorboard>=2.3.0
    - imageio>=2.8.0
    - imageio-ffmpeg>=0.4.2
    - PyQtWebEngine>=5.15.1
    - simplification>=0.5.7
    - dataclasses>=0.6; python_version < '3.7'