# Installs dependencies for Annolid managed by Anaconda. 
#
name: annolid-dev
#prefix: /path/to/my/envs/annolid-dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.7.6
  - pip
  - cython 
  - pytorch::torchvision
  - pytorch::pytorch >=1.4.0
  - cudatoolkit
  - cudnn
  - ffmpeg
  - pytorch::cuda100
  - matplotlib
  - git 
  - curl 
  - unzip
  - pyqt
  - opencv
  - pyqtwebengine 
  - conda-forge::bash
  - numpy>=1.18.2
  - scipy>=1.5.2
  - easydict>=1.9
  - pip:
    - pillow>=8.3.1 
    # needed on KDE/Qt envs for matplotlib
    - labelme>=4.5.6
    - PyYAML>=5.3
    - decord>=0.4.0
    - pandas>=1.1.3
    - pycocotools>=2.0.2
    - tensorboard>=2.3.0
    - imageio>=2.8.0
    - imageio-ffmpeg>=0.4.2
    - simplification>=0.5.7
    - dataclasses>=0.6; python_version < '3.7'
    - jupyter-book==0.12.1
    - e .